#The name of your workflow.
name:  Test, build and deploy
# Trigger the workflow on push or pull request
on: 
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
#A workflow run is made up of one or more jobs. Jobs run in parallel by default.
jobs:
  build_deploy:
    #if conditional to prevent a job from running
    if: github.event_name != 'pull_request'
    runs-on: macos-latest
    #Identifies any jobs that must complete successfully before this job will run.
    name: Build  apk  and web
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      # This action sets up a java environment
      # https://github.com/actions/setup-java
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      #enable linux,macos,windows   and  web
      - run: flutter  config --enable-web
      - run: flutter  config --enable-linux-desktop
      - run: flutter  config --enable-macos-desktop
      - run: flutter  config --enable-windows-desktop
      - run: flutter pub get
      - run: flutter create --platforms=windows,macos,linux .
      # build macOS desktop version
      - run: flutter build macos --release
      # build Android version
      - run: flutter build apk --debug --split-per-abi
      # This action will create a github release and optionally upload an artifact to it.
      # https://github.com/ncipollo/release-action
      - name: Create a Release APK
        uses: ncipollo/release-action@v1
        with:
          tag: Realease 0.1v
          artifacts: "build/app/outputs/apk/debug/*.apk,build/macos/Build/Products/Release/*.app"
          token: ${{ secrets.GITHUB_TOKEN }}
      # build Flutter web version
      - run: flutter build web
      # Handle the deploy process of your project to GitHub Pages.
      # https://github.com/JamesIves/github-pages-deploy-action
      - uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          BASE_BRANCH: main
          BRANCH: gh-pages
          FOLDER: build/web
